[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model = { path = "../model" }
server = { path = "../server" }
gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git" }